server:
  port: 8080

spring:
  application:
    name: GameNote
  datasource:
    url: jdbc:postgresql://localhost:5440/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

igdb:
  client-id: ${IGDB_CLIENT_ID}
  client-secret: ${IGDB_CLIENT_SECRET}
  token-url: https://id.twitch.tv/oauth2/token
  api-url: https://api.igdb.com/v4