-- Schéma tel qu'il existait avant l'arrivée de Flyway, c'est-à-dire tel qu'Hibernate le
-- générait avec ddl-auto=update.
--
-- Cette migration ne s'exécute que sur une base vide. Les installations existantes — le
-- poste de développement, et la pile docker dont le script d'init recrée déjà ce schéma —
-- sont marquées à cette version sans la rejouer (spring.flyway.baseline-on-migrate).
-- Les noms de contraintes sont ceux, lisibles, qu'on aurait choisis : Hibernate ne vérifie
-- que les tables, les colonnes et leurs types, jamais le nom des contraintes.

CREATE TABLE app_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(50)  NOT NULL UNIQUE,
    email         varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    avatar_url    text,
    bio           text,
    role          varchar(20) CHECK (role IN ('USER', 'ADMIN')),
    created_at    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone
);

CREATE TABLE game_rating (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint       NOT NULL,
    igdb_game_id bigint       NOT NULL,
    title        varchar(255) NOT NULL,
    cover_url    varchar(255),
    release_date bigint,
    summary      text,
    rating       integer      NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone,
    CONSTRAINT uk_game_rating_user_game UNIQUE (user_id, igdb_game_id)
);

CREATE TABLE game_rating_genre (
    game_rating_id bigint NOT NULL REFERENCES game_rating (id),
    genre          varchar(100)
);

CREATE TABLE game_rating_developer (
    game_rating_id bigint NOT NULL REFERENCES game_rating (id),
    developer      varchar(255)
);

CREATE TABLE game_rating_publisher (
    game_rating_id bigint NOT NULL REFERENCES game_rating (id),
    publisher      varchar(255)
);

CREATE TABLE game_rating_platform (
    game_rating_id bigint NOT NULL REFERENCES game_rating (id),
    platform       varchar(100)
);

CREATE TABLE game_comment (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint NOT NULL,
    igdb_game_id bigint NOT NULL,
    content      text   NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone,
    CONSTRAINT uk_game_comment_user_game UNIQUE (user_id, igdb_game_id)
);

CREATE INDEX idx_game_comment_game ON game_comment (igdb_game_id);

CREATE TABLE game_skip (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint NOT NULL,
    igdb_game_id bigint NOT NULL,
    skipped_at   timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_game_skip_user_game UNIQUE (user_id, igdb_game_id)
);

CREATE INDEX idx_game_skip_user_skipped_at ON game_skip (user_id, skipped_at);
