-- Point 4 : suivre un joueur.
--
-- Relation orientée : suivre quelqu'un ne demande pas son accord et n'entraîne pas la
-- réciproque. La contrainte d'unicité rend le suivi idempotent, et le CHECK interdit à un
-- compte de se suivre lui-même — ce qui polluerait son propre fil d'activité.

CREATE TABLE user_follow (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    followed_id bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_user_follow UNIQUE (follower_id, followed_id),
    CONSTRAINT ck_user_follow_not_self CHECK (follower_id <> followed_id)
);

-- L'unicité couvre déjà les lectures « qui je suis » ; l'index inverse sert au compteur
-- d'abonnés affiché sur un profil.
CREATE INDEX idx_user_follow_followed ON user_follow (followed_id);
