-- Point 5 : marquer un avis comme utile.
--
-- Une ligne par (avis, votant) : la contrainte d'unicité fait tout le travail, le second
-- clic retire la réaction au lieu d'en ajouter une deuxième. Aucun champ « type » n'est
-- prévu, le geste est unique et volontairement non conflictuel.

CREATE TABLE comment_reaction (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES game_comment (id) ON DELETE CASCADE,
    user_id    bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_comment_reaction UNIQUE (comment_id, user_id)
);

-- Le comptage « combien de personnes ont trouvé cet avis utile » est la lecture principale.
CREATE INDEX idx_comment_reaction_comment ON comment_reaction (comment_id);
