-- Point 6 : listes personnalisées (« Mon top 10 2026 », « Les meilleurs metroidvanias »).
--
-- Chaque liste appartient à un membre et choisit d'être publique ou privée. L'ordre est
-- celui que l'auteur décide, porté par `sort_index` : dans un top, la place compte autant
-- que la présence. La colonne ne s'appelle pas `position`, qui est une fonction SQL et
-- obligerait à des guillemets partout.
--
-- Un élément recopie titre et jaquette : une liste peut contenir un jeu que personne n'a
-- noté, dont le site n'a donc aucune autre trace, et l'afficher ne doit pas dépendre d'un
-- appel à IGDB.

CREATE TABLE game_list (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    name        varchar(100) NOT NULL,
    description varchar(500),
    visibility  varchar(20)  NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    updated_at  timestamp(6) with time zone,
    CONSTRAINT ck_game_list_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

CREATE INDEX idx_game_list_user ON game_list (user_id);

CREATE TABLE game_list_item (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_list_id bigint       NOT NULL REFERENCES game_list (id) ON DELETE CASCADE,
    igdb_game_id bigint       NOT NULL,
    title        varchar(255) NOT NULL,
    cover_url    varchar(255),
    release_date bigint,
    note         varchar(280),
    sort_index   integer      NOT NULL,
    added_at     timestamp(6) with time zone NOT NULL,
    -- Un même jeu ne peut figurer deux fois dans la même liste.
    CONSTRAINT uk_game_list_item UNIQUE (game_list_id, igdb_game_id)
);

CREATE INDEX idx_game_list_item_order ON game_list_item (game_list_id, sort_index);
