-- Point 13 : file de signalements de la console d'administration.
--
-- Le signalement conserve une copie du texte visé et l'identifiant de son auteur, et son
-- lien vers l'avis passe à NULL si celui-ci disparaît (ON DELETE SET NULL). Sans cette
-- copie, accepter un signalement — donc supprimer l'avis — effacerait du même coup la
-- trace de la décision : la console n'aurait plus d'historique, seulement une file qui se
-- vide. Ici, un signalement traité reste lisible avec ce qui l'a motivé.

CREATE TABLE comment_report (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id         bigint REFERENCES game_comment (id) ON DELETE SET NULL,
    reporter_id        bigint      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    reported_author_id bigint      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    igdb_game_id       bigint      NOT NULL,
    reported_content   text        NOT NULL,
    reason             varchar(20) NOT NULL,
    details            varchar(500),
    status             varchar(20) NOT NULL,
    created_at         timestamp(6) with time zone NOT NULL,
    handled_at         timestamp(6) with time zone,
    handled_by_id      bigint REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_comment_report_reason CHECK (reason IN ('SPAM', 'ABUSE', 'SPOILER', 'OFF_TOPIC', 'OTHER')),
    CONSTRAINT ck_comment_report_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    -- Un membre ne signale un avis donné qu'une fois. Les signalements dont l'avis a été
    -- supprimé portent un comment_id nul, que PostgreSQL ne considère jamais comme un
    -- doublon : l'historique peut donc s'accumuler sans gêner cette règle.
    CONSTRAINT uk_comment_report_reporter UNIQUE (comment_id, reporter_id)
);

-- La console ouvre sur « les signalements en attente, du plus ancien au plus récent ».
CREATE INDEX idx_comment_report_status ON comment_report (status, created_at);
